<?php

use Illuminate\Database\Seeder;

class RanksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {      
      DB::table('ranks')->insert([
        [
          'name' => 'Секретарь',
          'weight' => 1,
          'organization_id' => 1,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Адвокат',
          'weight' => 2,
          'organization_id' => 1,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Охрана',
          'weight' => 3,
          'organization_id' => 1,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Начальник охраны',
          'weight' => 4,
          'organization_id' => 1,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Министр',
          'weight' => 5,
          'organization_id' => 1,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Мэр',
          'weight' => 6,
          'organization_id' => 1,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Стажер',
          'weight' => 1,
          'organization_id' => 2,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Дежурный',
          'weight' => 2,
          'organization_id' => 2,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Мл. агент',
          'weight' => 3,
          'organization_id' => 2,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Агент GNK',
          'weight' => 4,
          'organization_id' => 2,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Агент CID',
          'weight' => 5,
          'organization_id' => 2,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Глава GNK',
          'weight' => 6,
          'organization_id' => 2,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Глава CID',
          'weight' => 7,
          'organization_id' => 2,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Инспектор',
          'weight' => 8,
          'organization_id' => 2,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Зам. директора',
          'weight' => 9,
          'organization_id' => 2,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Директор',
          'weight' => 10,
          'organization_id' => 2,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Кадет',
          'weight' => 1,
          'organization_id' => 3,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Офицер',
          'weight' => 2,
          'organization_id' => 3,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Мл. Сержант',
          'weight' => 3,
          'organization_id' => 3,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Сержант',
          'weight' => 4,
          'organization_id' => 3,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Прапорщик',
          'weight' => 5,
          'organization_id' => 3,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Старший Прапорщик',
          'weight' => 6,
          'organization_id' => 3,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Младший Лейтенант',
          'weight' => 7,
          'organization_id' => 3,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Лейтенант',
          'weight' => 8,
          'organization_id' => 3,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Старший лейтенант',
          'weight' => 9,
          'organization_id' => 3,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Капитан',
          'weight' => 10,
          'organization_id' => 3,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Майор',
          'weight' => 11,
          'organization_id' => 3,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Подполковник',
          'weight' => 12,
          'organization_id' => 3,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Полковник',
          'weight' => 13,
          'organization_id' => 3,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Шериф',
          'weight' => 14,
          'organization_id' => 3,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Кадет',
          'weight' => 1,
          'organization_id' => 4,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Офицер',
          'weight' => 2,
          'organization_id' => 4,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Мл. Сержант',
          'weight' => 3,
          'organization_id' => 4,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Сержант',
          'weight' => 4,
          'organization_id' => 4,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Прапорщик',
          'weight' => 5,
          'organization_id' => 4,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Старший Прапорщик',
          'weight' => 6,
          'organization_id' => 4,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Младший Лейтенант',
          'weight' => 7,
          'organization_id' => 4,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Лейтенант',
          'weight' => 8,
          'organization_id' => 4,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Старший лейтенант',
          'weight' => 9,
          'organization_id' => 4,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Капитан',
          'weight' => 10,
          'organization_id' => 4,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Майор',
          'weight' => 11,
          'organization_id' => 4,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Подполковник',
          'weight' => 12,
          'organization_id' => 4,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Полковник',
          'weight' => 13,
          'organization_id' => 4,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Шериф',
          'weight' => 14,
          'organization_id' => 4,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Кадет',
          'weight' => 1,
          'organization_id' => 5,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Офицер',
          'weight' => 2,
          'organization_id' => 5,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Мл. Сержант',
          'weight' => 3,
          'organization_id' => 5,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Сержант',
          'weight' => 4,
          'organization_id' => 5,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Прапорщик',
          'weight' => 5,
          'organization_id' => 5,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Старший Прапорщик',
          'weight' => 6,
          'organization_id' => 5,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Младший Лейтенант',
          'weight' => 7,
          'organization_id' => 5,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Лейтенант',
          'weight' => 8,
          'organization_id' => 5,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Старший лейтенант',
          'weight' => 9,
          'organization_id' => 5,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Капитан',
          'weight' => 10,
          'organization_id' => 5,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Майор',
          'weight' => 11,
          'organization_id' => 5,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Подполковник',
          'weight' => 12,
          'organization_id' => 5,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Полковник',
          'weight' => 13,
          'organization_id' => 5,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Шериф',
          'weight' => 14,
          'organization_id' => 5,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Рядовой',
          'weight' => 1,
          'organization_id' => 6,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Ефрейтор',
          'weight' => 2,
          'organization_id' => 6,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Мл. Сержант',
          'weight' => 3,
          'organization_id' => 6,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Сержант',
          'weight' => 4,
          'organization_id' => 6,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Старший сержант',
          'weight' => 5,
          'organization_id' => 6,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Старшина',
          'weight' => 6,
          'organization_id' => 6,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Прапорщик',
          'weight' => 7,
          'organization_id' => 6,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Младший лейтенант',
          'weight' => 8,
          'organization_id' => 6,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Лейтенант',
          'weight' => 9,
          'organization_id' => 6,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Старший лейтенант',
          'weight' => 10,
          'organization_id' => 6,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Капитан',
          'weight' => 11,
          'organization_id' => 6,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Майор',
          'weight' => 12,
          'organization_id' => 6,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Подполковник',
          'weight' => 13,
          'organization_id' => 6,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Полковник',
          'weight' => 14,
          'organization_id' => 6,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Генерал',
          'weight' => 15,
          'organization_id' => 6,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Рядовой',
          'weight' => 1,
          'organization_id' => 7,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Ефрейтор',
          'weight' => 2,
          'organization_id' => 7,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Мл. Сержант',
          'weight' => 3,
          'organization_id' => 7,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Сержант',
          'weight' => 4,
          'organization_id' => 7,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Старший сержант',
          'weight' => 5,
          'organization_id' => 7,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Старшина',
          'weight' => 6,
          'organization_id' => 7,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Прапорщик',
          'weight' => 7,
          'organization_id' => 7,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Младший лейтенант',
          'weight' => 8,
          'organization_id' => 7,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Лейтенант',
          'weight' => 9,
          'organization_id' => 7,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Старший лейтенант',
          'weight' => 10,
          'organization_id' => 7,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Капитан',
          'weight' => 11,
          'organization_id' => 7,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Майор',
          'weight' => 12,
          'organization_id' => 7,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Подполковник',
          'weight' => 13,
          'organization_id' => 7,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Полковник',
          'weight' => 14,
          'organization_id' => 7,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Генерал',
          'weight' => 15,
          'organization_id' => 7,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Стажер',
          'weight' => 1,
          'organization_id' => 9,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Консультант',
          'weight' => 2,
          'organization_id' => 9,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Экзаменатор',
          'weight' => 3,
          'organization_id' => 9,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Младший инструктор',
          'weight' => 4,
          'organization_id' => 9,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Инструктор',
          'weight' => 5,
          'organization_id' => 9,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Координатор',
          'weight' => 6,
          'organization_id' => 9,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Младший Менеджер',
          'weight' => 7,
          'organization_id' => 9,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Старший Менеджер',
          'weight' => 8,
          'organization_id' => 9,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Директор',
          'weight' => 9,
          'organization_id' => 9,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
        [
          'name' => 'Управляющий',
          'weight' => 10,
          'organization_id' => 9,
          'created_at' => \Carbon\Carbon::now(),
          'updated_at' => \Carbon\Carbon::now(),
        ],
      ]);
    }
}
